### ISSUE TITLE
Testing Chrome.ahk

### ISSUE THREAD

**Issue by dmtr99** [thqby/ahk2_lib#3]
I tested some v2 Chrome.ahk code, and It seems to be working great, thanks a lot for your amazing and usefull work :D

Currently the JSON is returning a map, but would it not be more logically to return an object?
I found it strange to get maps back.
I know V1 mixed Maps and Objects.
This would make it easier to change some old scripts to v2.

Working example v2:

```
ChromeInst :=  Chrome()
ChromeTab := ChromeInst.GetPage()
result := ChromeTab.Evaluate("window.location.href")
msgbox(result["value"])
```

Normally I would think that result.value should be the correct syntax.

**Comment by thqby** [comment]
Map supports case sensitivity, while object is not case sensitive, although it is rare to have keys with different cases at the same time.
And run `Map.Prototype.DefineProp('__get', {call: Map.Prototype.Get})`, you can use map just like object.

**Comment by dmtr99** [comment]
Interesting trick, thanks a lot.
Strange how it stays case sensitive, or you need to set the CaseSense Off before filling the object. in some strange cases you would indeed lose data and that is indeed a disadvantage to this approach, and maybe it is better to keep the code cleaner.

```
oMap := Map()
oMap.CaseSense := "Off"
oMap.Set("Red", "ff0000" , "Green", "00ff00", "Deep Blue", "0000ff")
oMap.DefineProp('__get', { call: oMap.Get })
MsgBox("oMap.red:" oMap.red "`noMap.Red:" oMap.Red)
```

**Comment by thqby** [comment]
Use an existing browser that starts in debug mode?

**Comment by dmtr99** [comment]
Yes, I have the habit to run my browser always in debug mode. In the V1 version you could connect to the existing debug window with this code.

**Comment by thqby** [comment]
This problem has been fixed.

**Comment by dmtr99** [comment]
Tested and approved.

Just for clarity, my previous code still does not work.

this seems to work perfectly:
```
ChromeInst := Chrome.FindInstances()
ChromeTab := ChromeInst.GetPage()
result := ChromeTab.Evaluate("window.location.href")
msgbox(result["value"])
```
